name: 'Automated quick-and-dirty build'
on: [push]
jobs:
  quick-and-dirty-build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
      - name: 'Build'
        uses: jeltsch/actions-isabelle-build@master
        with:
          session-name: Ouroboros
          chapter-name: IOG
          source-path: src
          isabelle-version: 2022
          afp-sessions:
            ZFC_in_HOL:2022-10-27
            Finite-Map-Extras:2022-10-27
          github-sessions:
            input-output-hk/thorn-calculus:src
